spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/demo_db
spring.datasource.username=tomoya
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver